package builtin

import "ccLoad/internal/protocol"

// Register installs the built-in protocol translators used by the proxy.
func Register(reg *protocol.Registry) {
	reg.RegisterRequest(protocol.OpenAI, protocol.Gemini, convertOpenAIRequestToGemini)
	reg.RegisterRequest(protocol.Gemini, protocol.OpenAI, convertGeminiRequestToOpenAI)
	reg.RegisterStreamResponse(protocol.Gemini, protocol.OpenAI, convertGeminiResponseToOpenAIStream)
	reg.RegisterStreamResponse(protocol.OpenAI, protocol.Gemini, convertOpenAIResponseToGeminiStream)
	reg.RegisterNonStreamResponse(protocol.Gemini, protocol.OpenAI, convertGeminiResponseToOpenAINonStream)
	reg.RegisterNonStreamResponse(protocol.OpenAI, protocol.Gemini, convertOpenAIResponseToGeminiNonStream)
	reg.RegisterRequest(protocol.OpenAI, protocol.Anthropic, convertOpenAIRequestToAnthropic)
	reg.RegisterStreamResponse(protocol.Anthropic, protocol.OpenAI, convertAnthropicResponseToOpenAIStream)
	reg.RegisterNonStreamResponse(protocol.Anthropic, protocol.OpenAI, convertAnthropicResponseToOpenAINonStream)
	reg.RegisterRequest(protocol.Anthropic, protocol.OpenAI, convertAnthropicRequestToOpenAI)
	reg.RegisterStreamResponse(protocol.OpenAI, protocol.Anthropic, convertOpenAIResponseToAnthropicStream)
	reg.RegisterNonStreamResponse(protocol.OpenAI, protocol.Anthropic, convertOpenAIResponseToAnthropicNonStream)
	reg.RegisterRequest(protocol.OpenAI, protocol.Codex, convertOpenAIRequestToCodex)
	reg.RegisterStreamResponse(protocol.Codex, protocol.OpenAI, convertCodexResponseToOpenAIStream)
	reg.RegisterNonStreamResponse(protocol.Codex, protocol.OpenAI, convertCodexResponseToOpenAINonStream)
	reg.RegisterRequest(protocol.Anthropic, protocol.Gemini, convertAnthropicRequestToGemini)
	reg.RegisterStreamResponse(protocol.Gemini, protocol.Anthropic, convertGeminiResponseToAnthropicStream)
	reg.RegisterNonStreamResponse(protocol.Gemini, protocol.Anthropic, convertGeminiResponseToAnthropicNonStream)
	reg.RegisterRequest(protocol.Gemini, protocol.Anthropic, convertGeminiRequestToAnthropic)
	reg.RegisterStreamResponse(protocol.Anthropic, protocol.Gemini, convertAnthropicResponseToGeminiStream)
	reg.RegisterNonStreamResponse(protocol.Anthropic, protocol.Gemini, convertAnthropicResponseToGeminiNonStream)
	reg.RegisterRequest(protocol.Codex, protocol.Gemini, convertCodexRequestToGemini)
	reg.RegisterStreamResponse(protocol.Gemini, protocol.Codex, convertGeminiResponseToCodexStream)
	reg.RegisterNonStreamResponse(protocol.Gemini, protocol.Codex, convertGeminiResponseToCodexNonStream)
	reg.RegisterRequest(protocol.Gemini, protocol.Codex, convertGeminiRequestToCodex)
	reg.RegisterStreamResponse(protocol.Codex, protocol.Gemini, convertCodexResponseToGeminiStream)
	reg.RegisterNonStreamResponse(protocol.Codex, protocol.Gemini, convertCodexResponseToGeminiNonStream)
	reg.RegisterRequest(protocol.Codex, protocol.Anthropic, convertCodexRequestToAnthropic)
	reg.RegisterStreamResponse(protocol.Anthropic, protocol.Codex, convertAnthropicResponseToCodexStream)
	reg.RegisterNonStreamResponse(protocol.Anthropic, protocol.Codex, convertAnthropicResponseToCodexNonStream)
	reg.RegisterRequest(protocol.Anthropic, protocol.Codex, convertAnthropicRequestToCodex)
	reg.RegisterStreamResponse(protocol.Codex, protocol.Anthropic, convertCodexResponseToAnthropicStream)
	reg.RegisterNonStreamResponse(protocol.Codex, protocol.Anthropic, convertCodexResponseToAnthropicNonStream)
	reg.RegisterRequest(protocol.Codex, protocol.OpenAI, convertCodexRequestToOpenAI)
	reg.RegisterStreamResponse(protocol.OpenAI, protocol.Codex, convertOpenAIResponseToCodexStream)
	reg.RegisterNonStreamResponse(protocol.OpenAI, protocol.Codex, convertOpenAIResponseToCodexNonStream)
}
